# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86d8b3f1192a2f64ccb29384b34639109c1694aced7f2a488aac7db5bd082dea4fcf684e0f3ca51a573c0543149c52779f97d96281c0dd49afdcf32cd3edc149

test:
  secret_key_base: be38e9428c5f67e8e864b2cfcdb3d22defa5b3110c3b92ca26a8aa1450fea097b4de85d1859ccd9cdfc45e4d6e063076847d5b749b61b9808242a2784b4b7943

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
